### ISSUE TITLE
Error exporting X-Plane obj

### ISSUE THREAD

**Issue by xabi27** [der-On/XPlane2Blender#180]
Hi everyone. I am doing an object for my scenery and when I try to export to x-plane, the Blender gives me an error.
Appears a message saying: RuntimeError: ordered dict mutated during iteration And more things
Image https://plus.google.com/u/0/photos/photo/106416824782203424155/6281246946638514178
Thanks for doing this excellent addon

**Comment by xabi27** [comment]
Traceback (most recent call last):
  File "/Users/--/Desktop/blender_scripts/addons/io_xplane2blender/xplane_export.py", line 1771, in execute
    data.collect()
  File "/Users/--/Desktop/blender_scripts/addons/io_xplane2blender/xplane_export.py", line 1329, in collect
    self.collectObjects(self.getObjectsByLayer(layer),filename)
  File "/Users/--/Desktop/blender_scripts/addons/io_xplane2blender/xplane_export.py", line 1438, in collectObjects
    prim = XPlanePrimitive(obj,parent)
  File "/Users/--/Desktop/blender_scripts/addons/io_xplane2blender/xplane_types.py", line 889, in __init__
    self.material = XPlaneMaterial(self.object)
  File "/Users/--/Desktop/blender_scripts/addons/io_xplane2blender/xplane_types.py", line 1138, in __init__
    self.attributes.order()
  File "/Users/--/Desktop/blender_scripts/addons/io_xplane2blender/xplane_types.py", line 103, in order
    for name in self:
RuntimeError: OrderedDict mutated during iteration

location: <unknown location>:-1

**Comment by airfightergr** [comment]
Make sure that you check the log file which displays the error in plain language.

https://plus.google.com/u/0/+IliasTselios/posts/3z9FZdtE7eA?pid=6281311629914216322&oid=100396994549681477095

1. In blender, at any window, click the icon at the left bottom corner and select the Text Editor.
2. Click the "notepad" icon and select the xplane2blender.log to view the log file.

**Comment by xabi27** [comment]
Here is the log:
scanning Camera
scanning Point.001
	 Point.001: adding to list
		 checking animations of Point.001
scanning Point
	 Point: adding to list
		 checking animations of Point
scanning Finger1
	 Finger1: adding to list

**Comment by xabi27** [comment]
Fixed, i downloaded the v2.76 and works
