### ISSUE TITLE
Plugin throws exception when set to root mode, collectFromBlenderRootObject throws KeyError

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#212]
When attempting to export any blender via Root Object mode collectFromBlenderRootObject throws KeyError on line 321.

```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\Ted\Desktop\Utilities\Media\blender-2.78b-windows64\2.78\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Ted\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_blender2xplane\xplane_export.py", line 88, in execute
    xplaneFiles = xplane_file.createFilesFromBlenderRootObjects(bpy.context.scene)
  File "C:\Users\Ted\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_blender2xplane\xplane_types\xplane_file.py", line 99, in createFilesFromBlenderRootObjects
    xplaneFile = createFileFromBlenderRootObject(blenderObject)
  File "C:\Users\Ted\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_blender2xplane\xplane_types\xplane_file.py", line 90, in createFileFromBlenderRootObject
    xplaneFile.collectFromBlenderRootObject(blenderObject)
  File "C:\Users\Ted\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\io_blender2xplane\xplane_types\xplane_file.py", line 321, in collectFromBlenderRootObject
    rootXPlaneObject = self.objects[blenderRootObject.name]
KeyError: 'Empty'

location: C:\Users\Ted\Desktop\Utilities\Media\blender-2.78b-windows64\2.78\scripts\modules\bpy\ops.py:189
```

**Comment by tngreene** [comment]
fixed a while ago, but only made it into a commit last month: 6b10cdbf9f4faf197e
